### ISSUE TITLE
关于电池问题

### ISSUE THREAD

**Issue by CaelestisAstesia** [B1ueKi11e3/RuiyiCrack#4]
许多地方已经被发现电池，于是ry使用了ota升级包使电池嗝屁。希望大家群策群力，把电池弄回来，我讲讲我的思路
思路如下：
rootTB-X605M，使用钛备份复制整个有电池的系统，然后用rec升级即可
root的思路，解锁bl，但是目前只能进入recovery和9008模式
按道理说9008模式可以刷很多任何东西，但由于缺少正确的引导文件
所以问题的关键在于解锁bl和root，靠大家了！

**Comment by B1ueKi11e3** [comment]
群内有个吊大的有引导文件
